services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
      PGTZ: ${TZ}
    container_name: ${PROJECT_NAME}-timescaledb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./api/gen/specs/openapi/openapi.yaml:/openapi.yaml
    container_name: ${PROJECT_NAME}-swagger

volumes:
  pgdata: