openapi: 3.0.3
info:
  title: Audit Logging API
  version: 1.0.0
servers:
- url: '{host}/api/v1'
  variables:
    host:
      default: http://localhost:38081
      enum:
      - http://localhost:38081
tags:
- description: Tenant API
  name: Tenants
- description: Log API
  name: Logs
paths:
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
          description: pet response
  /tenants:
    get:
      description: List accessible tenants (admin only)
      operationId: ListTenants
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Tenant'
                type: array
          description: Successful operation
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Access Forbidden (admin only)
      security:
      - BearerAuth: []
      tags:
      - Tenants
    post:
      operationId: CreateTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: Successful operation
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Access Forbidden (admin only)
      security:
      - BearerAuth: []
      tags:
      - Tenants
components:
  schemas:
    Tenant:
      example:
        updated_at: 2025-08-19T20:28:12Z
        name: My Tenant
        created_at: 2025-08-19T20:28:12Z
        id: 123e4567-e89b-12d3-a456-426655440000
      properties:
        id:
          description: uuid string
          example: 123e4567-e89b-12d3-a456-426655440000
          type: string
        name:
          example: My Tenant
          type: string
        created_at:
          description: Timestamp
          example: 2025-08-19T20:28:12Z
          type: string
        updated_at:
          description: Timestamp
          example: 2025-08-19T20:28:12Z
          type: string
      required:
      - created_at
      - id
      - name
      - updated_at
      type: object
    Error:
      properties:
        type:
          default: internal_error
          enum:
          - validation_failed
          - permission_denied
          - request_not_found
          - internal_error
          type: string
        code:
          description: Custom error code
          type: string
        title:
          description: Error Summary
          type: string
        detail:
          description: Detailed error description
          type: string
      required:
      - code
      - detail
      - title
      - type
      type: object
    CreateTenantRequestBody:
      example:
        name: My Tenant
      properties:
        name:
          example: My Tenant
          type: string
      required:
      - name
      type: object
    Pong:
      example:
        ping: pong
      properties:
        ping:
          example: pong
          type: string
      required:
      - ping
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      description: Bearer token
      scheme: bearer
      type: http
